version: '3.3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  sflow:
    image: sflow/prometheus
    ports:
      - "6343:6343/udp"
      - "8008:8008"
    restart: always

  prometheus:
    image: prom/prometheus
    depends_on:
      - sflow
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: "grafana/grafana"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources
      - grafana_data:/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    restart: always
